### PR TITLE
Browserfiying the module

### PR DESCRIPTION
**Pull request by Wilkins**
Adding the npm module, the Grunt config, and a mockup of the lib-cov module to be able to browserify without errors. Everything seems OK.

### CODE REVIEW

**Comment by elliotstokes** [comment]
ah also need to remove the gpx-parse file from the commit.

**Comment by Wilkins** [comment]
You want to remove the browserified file from the repository ? Or juste change the name ?

**Comment by elliotstokes** [comment]
I think probably remove it as its a generated file.

**Comment by elliotstokes** [comment]
Unless you have a reason why you want to add it?

**Comment by Wilkins** [comment]
Well, yeah I wish it was already included in the repository. So this repository could be included as a git submodule in other projects, and be used out of the box.
For example, in the project I'm working on, I use gpx-parse as a submodule. I want the module to be pulled when I clone the repository, and I want it to be included in my javascript when I run Grunt, without having to know how to browserify this particular repository. Each repository should be built already.
See some examples: 
- https://github.com/tyrasd/togpx
- https://github.com/mapbox/tokml
This is my opinion, of course this is your repository, your choice :-)

**Comment by elliotstokes** [comment]
How about we put it in a folder called dist?

**Comment by Wilkins** [comment]
Perfect for me.

**Comment by elliotstokes** [comment]
Im not sure I can edit this push so are you able to make the modification to the grunt script to build to a dist folder and commit the browserify file into that folder instead? Ill merge it all then.

**Comment by Wilkins** [comment]
Yeah no problem, I'll do theses modifications in few hours. I'm closing this PR, I will open a new one.

**Comment by elliotstokes** [comment]
No probs. Ill check back later. Thanks again

**Pull request closed without merging**
